services:
  stats-db:
    image: postgres:17.0
    container_name: stats-db
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB: stats-db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test

  stats-server:
    build: stats/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db

volumes:
  pgdata:
