version: '3.8'

services:
  stats-db:
    image: postgres:17
    container_name: stats-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./stats/stats-server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_DB: stats_db
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: pgadmin

  stats-server:
    build: stats/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db

  ewm-db:
    image: postgres:17
    container_name: ewm-db
    ports:
      - "5433:5432"
    volumes:
     - ./ewm-service/ewm/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_DB: ewm_db
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: pgadmin

  ewm-service:
    build: ./ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      SPRING_BOOT_DEBUG: true
